#
# SELinux policy module RPMs build
#
name: "Build RPM and DEB packages to install compiled SELinux policy module"

concurrency: 
  group: SELinux_compile_wkf_group

on:
  release:
    types: [ published ]
  
  workflow_dispatch:
         
jobs:
  get_release_info:
    name: Get release info
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.get_release_url.outputs.upload_url }}
      version_number: ${{ steps.get_release_version.outputs.version }}
      release_number: ${{ steps.get_release_version.outputs.release }}

    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Get release upload URL
        id: get_release_url
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
       
      - name: Retrieve version and release numbers
        id: get_release_version
        run: |
          version_from_tag=$( echo "${{ github.ref_name }}" | sed -E 's,^v?([0-9]+\.[0-9]+\.[0-9]+).*$,\1,' )
          release_from_tag=$( echo "${{ github.ref_name }}" | sed -E 's,^v?[0-9]+\.[0-9]+\.[0-9]+(-([0-9]+))?.*$,\2,' )
          [ -z "${release_from_tag}" ] && release_from_tag=0
          echo "version=${version_from_tag}" >> $GITHUB_OUTPUT
          echo "release=${release_from_tag}" >> $GITHUB_OUTPUT
  
  build_RPMs:
    name: Build RPMs and upload them to release
    needs: get_release_info
    uses: lhqg/build_selinux_packages/.github/workflows/build_semodule_rpm.yml@main
    secrets:
      gpg_private_key: ${{ secrets.RPM_SIGNING_KEY }}
      gpg_private_key_password: ${{ secrets.RPM_SIGNING_KEY_PASSWORD }}
    with:
      spec_file_location: rpm/
      selinux_files_location: se_module/
      release_upload_url: ${{ needs.get_release_info.outputs.upload_url }}
      provided_version: ${{ needs.get_release_info.outputs.version_number }}
      provided_release: ${{ needs.get_release_info.outputs.release_number }}
      
  build_DEBs:
    name: Build Debian/Ubuntu packages and upload them to release
    needs: get_release_info
    uses: lhqg/build_selinux_packages/.github/workflows/build_semodule_deb.yml@main
    secrets:
      gpg_private_key: ${{ secrets.RPM_SIGNING_KEY }}
      gpg_private_key_password: ${{ secrets.RPM_SIGNING_KEY_PASSWORD }}
    with:
      build_material_dir: dpkg/
      release_upload_url: ${{ needs.get_release_info.outputs.upload_url }}
      package_version: ${{ needs.get_release_info.outputs.version_number }}
      