name: Changelog CI

on:
  pull_request:
    types: [ opened ]

  workflow_dispatch:
    inputs:
        release_version:
          required: true
          type: string
          description: 'Target (last) version for the changelog to be generated'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          release_version: ${{ inputs.release_version }}
          config_file: changelog-ci-config.yml
