name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * 1"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has not had any recent activity.  It will be closed in 7 days if it makes no further progress.'
        close-issue-message: 'Closing stale PR.'
        stale-pr-message: 'This PR has not had any recent activity.  It will be closed in 7 days if it makes no further progress.'
        close-pr-message: 'Closing stale PR.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'question,help wanted'
        exempt-pr-labels: 'question,external bug,external dependency'
